/*
 * @lc app=leetcode id=389 lang=c
 *
 * [389] Find the Difference
 *
 * https://leetcode.com/problems/find-the-difference/description/
 *
 * algorithms
 * Easy (60.51%)
 * Likes:    3028
 * Dislikes: 394
 * Total Accepted:    419.9K
 * Total Submissions: 694K
 * Testcase Example:  '"abcd"\n"abcde"'
 *
 * You are given two strings s and t.
 * 
 * String t is generated by random shuffling string s and then add one more
 * letter at a random position.
 * 
 * Return the letter that was added to t.
 * 
 * 
 * Example 1:
 * 
 * 
 * Input: s = "abcd", t = "abcde"
 * Output: "e"
 * Explanation: 'e' is the letter that was added.
 * 
 * 
 * Example 2:
 * 
 * 
 * Input: s = "", t = "y"
 * Output: "y"
 * 
 * 
 * 
 * Constraints:
 * 
 * 
 * 0 <= s.length <= 1000
 * t.length == s.length + 1
 * s and t consist of lowercase English letters.
 * 
 * 
 */

// @lc code=start

char findTheDifference(char *s, char *t)
{
	int s_length = strlen(s);
	int t_length = strlen(t);
	int alphabet_table[26];
	memset(alphabet_table, 0, sizeof(int) * 26);

	for (int i = 0; i < s_length; i++)
		alphabet_table[s[i] - 'a']++;
	for (int i = 0; i < t_length; i++)
		if (alphabet_table[t[i] - 'a'] == 0)
			return t[i];
		else
			alphabet_table[t[i] - 'a']--;

	// To make compiler happy
	return 0;
}

// @lc code=end

// Accepted
// 54/54 cases passed (0 ms)
// Your runtime beats 100 % of c submissions
// Your memory usage beats 84.44 % of c submissions (5.7 MB)
